const books = [
  {
    "publishedDate": "",
    "title": "스틱",
    "engTitle": "",
    "author": "",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": "",
    "title": "사용자 스토리 맵 만들기",
    "engTitle": "",
    "author": "",
    "subTitle": "아이디어를 올바른 제품으로 만드는 여정",
    "imgSrc": "https://image.aladin.co.kr/product/17458/18/cover500/8966262325_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": "",
    "title": "비지니스 불패의 법칙",
    "engTitle": "",
    "author": "",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": "",
    "title": "불공평하고 불완전한 네덜란드 디자인 여행",
    "engTitle": "",
    "author": "",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/254/63/cover500/8970593837_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": "",
    "title": "글짜씨 16 : 타입 디자인",
    "engTitle": "",
    "author": "",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1972,
    "title": "다른 방식으로 보기",
    "engTitle": "The Way of Seeing",
    "author": "존 버거",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1949,
    "title": "스기우라 고헤이 잡지 디자인 반세기",
    "engTitle": "",
    "author": "",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/59/2/cover500/8989420350_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1936,
    "title": "기술복제시대의 예술작품(제 2판)",
    "engTitle": "Das Kunstwerk im Zeitalter seiner technischen Reproduzierbarkeit",
    "author": "발터 벤야민",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "한글 레터링 자료집 1950-1985",
    "engTitle": "",
    "author": "프로파간다",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/4865/76/cover500/8998143224_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2012,
    "title": "헬무트 뉴튼 사진집",
    "engTitle": "Helmut Newton Work",
    "author": "헬무트 뉴튼",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "레이아웃보다 아이디어"
  },
  {
    "publishedDate": 1981,
    "title": "이제껏 배운 그래픽 디자인 규칙은 다 잊어라. 이 책에 실린 것까지",
    "engTitle": ".Forget All the Rules You Ever Learned About Graphic Design, Including the Ones in this Book",
    "author": "밥 길",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/10995/72/cover500/8994207791_1.jpgg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2017,
    "title": "한글 타이포그래피 한글 서체 디자인 전문지 2350, ISSUE #1 Oct. 20172350press",
    "engTitle": "",
    "author": "2350press",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1951,
    "title": "내 문장이 그렇게 이상한가요?",
    "engTitle": "",
    "author": "김정선",
    "subTitle": "내가 쓴 글, 내가 다듬는 법",
    "imgSrc": "https://image.aladin.co.kr/product/7492/3/cover500/k752434117_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2015,
    "title": "타이포잔치 2017, 5회 국제 타이포그래피 비엔날레 - 몸과 타이포그래피",
    "engTitle": "Typojanchi 2017, The 5th International Typography Biennale - Body and Typography",
    "author": "타이포잔치",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1981,
    "title": "한글의 글자표현",
    "engTitle": "",
    "author": "김진평",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/18417/35/cover500/k492534252_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2016,
    "title": "모리사와 최정호 폰트: 한글 폰트의 DNA",
    "engTitle": "Morisawa Choi Jeong-ho Fonts: DNA of Hangul Fonts",
    "author": "(주) 모리사와",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "그래픽 26호 2013.3 한글 타입과 레터링",
    "engTitle": "",
    "author": "프로파간다",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 0,
    "title": "한글 디자인 교과서",
    "engTitle": "",
    "author": "이용제, 안상수, 한재준",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2005,
    "title": "마이크로 타이포그래피",
    "engTitle": "Das Detail in der Typografie",
    "author": "요스트 호훌리, 워크룸 프레스 김형진",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/5047/55/cover500/8994207473_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "시각디자인: 좋은 것에 담긴 감각과 생각",
    "engTitle": "Critica portatile al visual design. Da Gutenberg ai social network",
    "author": "리카르도 팔치넬리, 윤병언",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/8652/38/cover500/k622535294_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "자신을 브랜딩하는 방법",
    "engTitle": "",
    "author": "CA 편집부, 이지은",
    "subTitle": "크리에이터의 가치를 높이는 사용 설명서",
    "imgSrc": "https://image.aladin.co.kr/product/3642/56/cover500/8997225170_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2017,
    "title": "모임꼴 2호",
    "engTitle": "",
    "author": "활자공간",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2016,
    "title": "섞어짜기 - 나만의 타이포그래피",
    "engTitle": "",
    "author": "문장현, 정재완, 심우진, 이경수, 최성민",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2016,
    "title": "모임꼴 창간호",
    "engTitle": "",
    "author": "이용제, 권진희, 최종원",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2010,
    "title": "비넬리의 디자인 원칙",
    "engTitle": "The Vignelli Canon",
    "author": "마시모 비넬리, 박효신",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/2589/80/letslook/8970596747_b.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "/ 객관화된 주관을 듣고 싶었기에 너무 고마운 책이었다."
  },
  {
    "publishedDate": 2011,
    "title": "그래픽 디자인의 요소",
    "engTitle": "The Elements of Graphic Design",
    "author": "알렉스 화이트, 안상락, 윤지선",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/2393/55/cover500/8997716158_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2012,
    "title": "로고 라이프",
    "engTitle": "Logo Life",
    "author": "론 판 데르 플루흐트",
    "subTitle": "로고는 살아있다. 세계 100대 로고의 탄생과 성장 스토리",
    "imgSrc": "https://image.aladin.co.kr/product/6570/31/cover500/k132433857_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2005,
    "title": "비주얼 그래머",
    "engTitle": "Visual Grammar",
    "author": "크리스티안 르보",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2011,
    "title": "폰트의 비밀",
    "engTitle": "",
    "author": "고바야시 아키라",
    "subTitle": "브랜드의 로고는 왜 고급스러워 보일까?",
    "imgSrc": "https://image.aladin.co.kr/product/3025/48/cover500/8970845054_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2015,
    "title": "마이크로인터랙션",
    "engTitle": "Microinteractions",
    "author": "댄 새퍼, 정승녁, 인사이트",
    "subTitle": "디테일에 강한 인터랙션 디자인 ㅣ UX insight 시리즈",
    "imgSrc": "https://image.aladin.co.kr/product/5878/21/cover500/8966261191_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "고 Go : 칩 키드의 그래픽 디자인 가이드",
    "engTitle": "Go: A Kidd's Guide to Graphic Design",
    "author": "칩 키드, 이종 출판사",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/5005/64/cover500/8979291930_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1982,
    "title": "편집 디자인",
    "engTitle": "Editing by design, 2nd Edition",
    "author": "잰 화이트",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/3184/36/cover500/8970597034_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2015,
    "title": "텍스트와 타이포그래피",
    "engTitle": "Shaping Text",
    "author": "얀 미덴도르프",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/5564/61/cover500/8970597964_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2015,
    "title": "Do it! 프런트엔드 웹 디자인 입문",
    "engTitle": "",
    "author": "고경희",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/13415/72/cover500/k142532408_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "디자이너의 서체이야기",
    "engTitle": "",
    "author": "지콜론북",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/2624/50/cover500/8998656051_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "디자인력",
    "engTitle": "デザインセンスを身につける",
    "author": "우지 도모코",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/2509/9/cover500/8970596771_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2015,
    "title": "커버 - 북디자이너의 표지 이야기",
    "engTitle": "Cover",
    "author": "피터 멘델선드",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/6283/66/cover500/896196240x_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "시작, 인포그래픽",
    "engTitle": "pictogram x diagram = infographic たのしい インフォグラフィック入門",
    "author": "사쿠라다 준",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/4438/15/cover500/8970597484_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2009,
    "title": "타이포그래피 불변의 법칙 100가지",
    "engTitle": "Typography essentials : 100 design principles for working with type",
    "author": "아이나 살츠",
    "subTitle": "타이포그래피로 디자인을 업그레이드 하라",
    "imgSrc": "https://image.aladin.co.kr/product/751/0/cover500/8979301987_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2010,
    "title": "타이포그래피 들여다보기",
    "engTitle": "Thinking with type, rivised edition",
    "author": "앨런 립튼 / 김성학 옮김",
    "subTitle": "타이포그래피 역사에서 미래까지, 이론에서 기술까지",
    "imgSrc": "https://image.aladin.co.kr/product/3315/0/cover500/8997716328_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2010,
    "title": "타이포그래피의 탄생",
    "engTitle": "From Gutenberg to Opentype",
    "author": "로빈 도드",
    "subTitle": "구텐베르크부터 디지털 폰트까지",
    "imgSrc": "https://image.aladin.co.kr/product/647/6/cover500/8993941130_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2010,
    "title": "허브 루발린",
    "engTitle": "Herb Lubalin: Art Director, Graphic Designer and Typographer",
    "author": "앨런 페콜릭",
    "subTitle": "아트디렉터, 타이포그래퍼, 그래픽 디자이너",
    "imgSrc": "https://image.aladin.co.kr/product/687/47/cover500/8992607512_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "디자이너의 흥미로운 물건들, 취향DESIGNER'S FAVORITE STUFF김선미, 장민",
    "engTitle": "",
    "author": "김선미, 장민",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2009,
    "title": "수전 손택의 일기와 노트수전 손택, 데이비드 리프 / 못 읽겠다. 읽다가 말았당",
    "engTitle": "",
    "author": "수전 손택, 데이비드 리프",
    "subTitle": "",
    "imgSrc": "/ 못 읽겠다. 읽다가 말았당",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2009,
    "title": "디자이너가 꼭 알아야 할 타이포그래피",
    "engTitle": "Type rules! : the designer's guide to professional typography",
    "author": "아이린 스트리즈버 / 디자인하우스",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/476/22/cover500/8970415289_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "One Page 인포그래픽 사용설명서, 메타포",
    "engTitle": "",
    "author": "우석진",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/4375/67/cover500/8998001039_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "크리에이터의 즐겨찾기",
    "engTitle": "Creator's Bookmarks",
    "author": "지콜론북 편집부",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/2388/93/cover500/8998656000_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2008,
    "title": "얀 치홀트, 타이포그래피의 거장. 그의 삶과 작품 그리고 유산",
    "engTitle": "JAN TSCHICHOLD, Structure and Content for Screenwriters",
    "author": "시즈 드 종, 알스톤 퍼바스, 마틴 르 콜트레, 리처드 B. 더블데이, 한스 라이하르트",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/769/81/cover500/8992607539_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2005,
    "title": "영혼을 잃지 않는 디자이너 되기",
    "engTitle": "How to be a graphic designer, without losing your soul",
    "author": "아드리안 쇼네시 / 김형진 유진민 옮김",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/88/26/cover500/8983713267_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2008,
    "title": "그리드Grids개빈 앰브로즈, 폴 해리스",
    "engTitle": "",
    "author": "개빈 앰브로즈, 폴 해리스",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2008,
    "title": "그래픽 디자인 : 새로운 기초",
    "engTitle": "Graphic Design: The New Basics",
    "author": "엘런 럽튼, 제니퍼 콜 필립스 / 원유홍 옮김",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/430/19/cover500/8992607350_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1948,
    "title": "문장강화文章講話",
    "engTitle": "",
    "author": "이태준",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2004,
    "title": "타이포그래피 천일야화",
    "engTitle": "",
    "author": "원유홍, 서승연",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/20517/46/cover500/8970595112_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1994,
    "title": "한번은,",
    "engTitle": "Einmal",
    "author": "빔 벤더스",
    "subTitle": "빔 벤더스의 사진 그리고 이야기들",
    "imgSrc": "https://image.aladin.co.kr/product/1253/72/cover500/8954615406_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1981,
    "title": "",
    "engTitle": "",
    "author": "에밀 루더",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 0,
    "title": "타이포그래피 에세이",
    "engTitle": "양을 훔친 당신에게 필요한 타이포그래피 지침서",
    "author": "에릭 슈피커만 & E, M 진저",
    "subTitle": "양을 훔친 당신에게 필요한 타이포그래피 지침서",
    "imgSrc": "https://image.aladin.co.kr/product/4766/34/cover500/8970597573_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2014,
    "title": "Do it! 자바스크립트+제이쿼리 입문 정인용",
    "engTitle": "",
    "author": "정인용",
    "subTitle": "",
    "imgSrc": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2013,
    "title": "Do it! HTML5 + CSS3 웹 표준의 정석",
    "engTitle": "",
    "author": "고경희",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/22267/44/cover500/k832636825_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 2004,
    "title": "그리드 디자인",
    "engTitle": "Grid Systems: Principles of Organizing Type",
    "author": "킴벌리 일램",
    "subTitle": "효율적인 타이포그래피 레이아웃의 원리",
    "imgSrc": "https://image.aladin.co.kr/product/59/92/cover500/8995724404_1.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  },
  {
    "publishedDate": 1935,
    "title": "타이포그라픽 디자인",
    "engTitle": "Typographische Gestaltung",
    "author": "얀 치홀트",
    "subTitle": "",
    "imgSrc": "https://image.aladin.co.kr/product/3627/50/cover500/8970597239_2.jpg",
    "": "",
    "__1": "",
    "__2": "",
    "__3": ""
  }
]

export default books