/**
 * 제품에서 뜻이 고정된 아이콘의 의미 이름과 iconoir 이름의 대응표.
 * 카테고리 묶음이 원본이고 ICON_NAMES는 이를 펼친 조회용 맵이므로,
 * 새 아이콘을 맞는 카테고리에 넣으면 문서 페이지의 목록에도 함께 나온다.
 */
export const ICON_CATALOG = {
  actions: {
    ADD: 'plus',
    ADD_CIRCLE: 'plus-circle-solid',
    DISMISS: 'xmark',
    CLOSE: 'xmark',
    CLEAR: 'xmark',
    COPY: 'copy',
    COPY_SUCCESS: 'check',
    DELETE: 'trash',
    FILTER: 'filter',
    INCREASE: 'plus',
    IMPORT: 'import',
    LOG_OUT: 'log-out',
    MORE_ACTIONS: 'more-vert',
    SHOW_MORE: 'more-horiz',
    DECREASE: 'minus',
    REFRESH: 'refresh',
    RETRY: 'refresh-double',
    SETTINGS: 'settings',
    SUBMIT: 'arrow-up',
    SHARE: 'arrow-up-right',
    CAMERA: 'camera',
    HIDE: 'eye-closed',
    VIEW: 'eye',
    THUMBS_UP: 'thumbs-up',
    DISLIKE: 'thumbs-down',
  },

  navigations: {
    BACK: 'arrow-left',
    COMPASS: 'compass',
    COLLAPSE: 'nav-arrow-up',
    EXPAND: 'nav-arrow-down',
    FORWARD: 'arrow-right',
    MENU: 'menu-scale',
    MENU_SIMPLE: 'menu',
    NAVIGATE_DOWN: 'arrow-down',
    OPEN_EXTERNAL: 'open-in-browser',
    PREVIOUS: 'arrow-left',
    NEXT: 'arrow-right',
    SCROLL_TOP: 'arrow-up',
  },

  indicators: {
    TREND_UP: 'graph-up',
    TREND_DOWN: 'graph-down',
  },

  status: {
    ERROR: 'xmark-circle',
    DONE: 'check-circle',
    INFO: 'info-circle',
    SUCCESS: 'check-circle',
    WARNING: 'warning-triangle',
    FAILURE: 'xmark-circle',
    IDLE: 'circle',
  },

  selection: {
    BOOKMARK: 'bookmark',
    BOOKMARK_SELECTED: 'bookmark-solid',
    CHECK: 'check',
    FAVORITE: 'star',
    FAVORITE_SELECTED: 'star-solid',
    LIKE: 'heart',
    LIKE_SELECTED: 'heart-solid',
    SELECTED: 'check-circle',
  },

  brand: {
    APPLE: 'apple',
    FACEBOOK: 'facebook',
    GITHUB: 'github',
    GOOGLE: 'google',
    INSTAGRAM: 'instagram',
    PINTEREST: 'pinterest',
    TWITTER: 'twitter',
  },

  theme: {
    BRUTAL_MODE: 'square',
    DARK_MODE: 'half-moon',
    GLASS_MODE: 'droplet',
    LIGHT_MODE: 'sun-light',
    PALETTE: 'palette',
    THEME: 'color-filter',
  },

  etc: {
    ARTICLE: 'book',
    BOLD: 'bold',
    BOOK: 'book',
    CODE: 'code',
    DESIGN: 'design-pencil',
    DOCUMENT: 'page',
    DOCUMENT_CHECK: 'clipboard-check',
    FLOWER: 'flower',
    GRAPH: 'graph-up',
    ITALIC: 'italic',
    LINK: 'link',
    MULTI_WINDOW: 'multi-window',
    TASK_LIST: 'task-list',
    UNDERLINE: 'underline',
    VIDEO: 'media-video',
    APP_WINDOW: 'app-window',
    BOX: 'box-iso',
    CREDIT_CARD: 'credit-card',
    CUBE_SCAN: 'cube-scan',
    DELIVERY: 'delivery-truck',
    PIPE: 'pipe-3d',
    GROUP: 'group',
    PEOPLE_TAG: 'people-tag',
    PROFILE: 'profile-circle',
    USER: 'user',
    USER_BADGE_CHECK: 'user-badge-check',
    CLICK: 'cursor-pointer',
    HELP_CIRCLE: 'help-circle',
    MOUSE_BUTTON: 'mouse-button-left',
    PLACE: 'city',
    SPARKS: 'sparks',
    WIFI: 'wifi',
    EMPTY: 'glass-empty',
    FIGMA: 'figma',
    XRAY: 'xray-view',
    ANNOUNCEMENT: 'megaphone',
    COMMENT: 'message',
    MAIL: 'mail',
    MAIL_IN: 'mail-in',
    NOTIFICATION: 'bell',
    REPLY: 'reply-to-message',
    GRID_VIEW: 'view-grid',
    HOME: 'air-conditioner',
    HOME_PAGE: 'home-simple-door',
    LIST_VIEW: 'table-rows',
    SORT: 'arrow-separate-vertical',
    DATE: 'calendar',
    FIELD: 'input-field',
    LOCK: 'lock',
    SEARCH: 'search',
    SUBTRACT: 'minus',
  },
} as const

export const ICON_NAMES = {
  ...ICON_CATALOG.actions,
  ...ICON_CATALOG.navigations,
  ...ICON_CATALOG.indicators,
  ...ICON_CATALOG.status,
  ...ICON_CATALOG.selection,
  ...ICON_CATALOG.brand,
  ...ICON_CATALOG.theme,
  ...ICON_CATALOG.etc,
} as const

export type IconName = typeof ICON_NAMES[keyof typeof ICON_NAMES]

/** 상태 톤마다 쓰는 아이콘. 톤을 가진 컴포넌트와 Feedback 문서가 함께 참조한다. */
export const STATUS_ICONS = {
  success: ICON_NAMES.SUCCESS,
  info: ICON_NAMES.INFO,
  warning: ICON_NAMES.WARNING,
  error: ICON_NAMES.ERROR,
  done: ICON_NAMES.DONE,
} as const

export type StatusTone = keyof typeof STATUS_ICONS
