export const SITEMAP = [
  // 1. 상단 독립 메뉴 (Top-level Links)
  {
    type: 'standalone',
    id: 'index',
    title: '홈',
    icon: 'home-simple-door',
  },
  {
    type: 'standalone',
    id: 'tokens',
    title: 'Tokens',
    icon: 'palette',
  },
  {
    type: 'standalone',
    id: 'signifier',
    title: 'Signifier',
    icon: 'design-pencil',
  },

  // 2. 카테고리 그룹 메뉴 (Dropdown Categories)
  {
    type: 'category',
    id: 'visual-information',
    title: 'Visual Information',
    icon: 'flower',
    items: [
      { id: 'avatar', name: 'avatar' },
      { id: 'list-row', name: 'list row' },
      { id: 'text', name: 'text' },
      { id: 'tag', name: 'tag' },
      { id: 'surface', name: 'surface' },
      { id: 'thumbnail', name: 'thumbnail' },
      { id: 'separator', name: 'separator' },
    ],
  },
  {
    type: 'category',
    id: 'actions',
    title: 'Actions',
    icon: 'mouse-button-left',
    items: [
      { id: 'button', name: 'button' },
      { id: 'icon-button', name: 'icon Button' },
      { id: 'toggle-button', name: 'toggle button' },
      { id: 'menuitem', name: 'menuItem' },
      { id: 'link', name: 'link' },
    ],
  },
  {
    type: 'category',
    id: 'navigations',
    title: 'Navigations',
    icon: 'nav-arrow-right',
    items: [
      { id: 'top-bar', name: 'top bar' },
      { id: 'bottom-bar', name: 'bottom bar' },
      { id: 'breadcrumb', name: 'breadcrumb', badge: '⚠️' },
      { id: 'tabs', name: 'tabs', subDir: 'patterns' },
    ],
  },
  {
    type: 'category',
    id: 'forms',
    title: 'Forms',
    icon: 'input-field',
    items: [
      { id: 'checkbox', name: 'checkbox' },
      { id: 'radio', name: 'radio' },
      { id: 'switch', name: 'switch' },
      { id: 'input', name: 'Input' },
      { id: 'searchfield', name: 'Search Field' },
      { id: 'textarea', name: 'Textarea' },
    ],
  },
  {
    type: 'category',
    id: 'feedbacks',
    title: 'Feedbacks',
    icon: 'reply-to-message',
    items: [
      { id: 'tooltip', name: 'tooltip' },
      { id: 'dialog', name: 'dialog' },
      { id: 'notice', name: 'notice' },
      { id: 'loading', name: 'loading' },
    ],
  },
  {
    type: 'category',
    id: 'patterns',
    title: 'Patterns',
    icon: 'city',
    items: [
      // { id: 'layout', name: 'layout' },
      { id: 'result', name: 'result' },
      { id: 'table', name: 'table', badge: '🚧' },
      { id: 'accordion', name: 'accordion' },
      { id: 'presentation', name: 'presentation' },
      { id: 'auth', name: 'auth' },
      { id: 'profile', name: 'user profile', badge: '🔥' },
      { id: 'chat', name: 'chat' },
      { id: 'setting', name: 'setting' },
      { id: 'post', name: 'post' },
      { id: 'product', name: 'Product' },
      { id: 'checkout', name: 'Checkout' },
      { id: 'class', name: 'Product 3 - class' },
    ],
  },
]
